#ifndef BRE_DOMAIN_MANUAL_RECOVERY_CANDIDATE_REGISTRY_STATUS_MQH
#define BRE_DOMAIN_MANUAL_RECOVERY_CANDIDATE_REGISTRY_STATUS_MQH

enum ENUM_BRE_MANUAL_RECOVERY_CANDIDATE_REGISTRY_STATUS
  {
   BRE_MANUAL_RECOVERY_CANDIDATE_AVAILABLE=0,
   BRE_MANUAL_RECOVERY_CANDIDATE_SELECTED,
   BRE_MANUAL_RECOVERY_CANDIDATE_SUBMITTED,
   BRE_MANUAL_RECOVERY_CANDIDATE_REJECTED,
   BRE_MANUAL_RECOVERY_CANDIDATE_EXPIRED,
   BRE_MANUAL_RECOVERY_CANDIDATE_EXECUTED
  };

class CManualRecoveryCandidateRegistryStatusText
  {
public:
   static string     ToString(const ENUM_BRE_MANUAL_RECOVERY_CANDIDATE_REGISTRY_STATUS status)
     {
      switch(status)
        {
         case BRE_MANUAL_RECOVERY_CANDIDATE_AVAILABLE: return "AVAILABLE";
         case BRE_MANUAL_RECOVERY_CANDIDATE_SELECTED: return "SELECTED";
         case BRE_MANUAL_RECOVERY_CANDIDATE_SUBMITTED: return "SUBMITTED";
         case BRE_MANUAL_RECOVERY_CANDIDATE_REJECTED: return "REJECTED";
         case BRE_MANUAL_RECOVERY_CANDIDATE_EXPIRED: return "EXPIRED";
         case BRE_MANUAL_RECOVERY_CANDIDATE_EXECUTED: return "EXECUTED";
         default:
           {
            ENUM_BRE_MANUAL_RECOVERY_CANDIDATE_REGISTRY_STATUS unreachable=status;
            return "UNKNOWN";
           }
        }
     }

   static bool       IsEligibleForManualSubmit(const ENUM_BRE_MANUAL_RECOVERY_CANDIDATE_REGISTRY_STATUS status)
     {
      return status==BRE_MANUAL_RECOVERY_CANDIDATE_AVAILABLE || status==BRE_MANUAL_RECOVERY_CANDIDATE_SELECTED;
     }
  };

#endif
