#ifndef BRE_DOMAIN_TRADING_SESSION_STATUS_MQH
#define BRE_DOMAIN_TRADING_SESSION_STATUS_MQH

enum ENUM_BRE_TRADING_SESSION_STATUS
  {
   BRE_TRADING_SESSION_UNKNOWN=0,
   BRE_TRADING_SESSION_OPEN,
   BRE_TRADING_SESSION_CLOSED
  };

#endif
