#ifndef BRE_DOMAIN_POSITION_SNAPSHOT_STATUS_MQH
#define BRE_DOMAIN_POSITION_SNAPSHOT_STATUS_MQH

enum ENUM_BRE_POSITION_SNAPSHOT_STATUS
  {
   BRE_POSITION_SNAPSHOT_OPEN=0,
   BRE_POSITION_SNAPSHOT_CLOSED
  };

#endif
