#ifndef BRE_DOMAIN_RECOVERY_RISK_BLOCK_REASON_MQH
#define BRE_DOMAIN_RECOVERY_RISK_BLOCK_REASON_MQH

#include <BasketRecovery/Domain/Risk/Enums/RiskViolationReason.mqh>

enum ENUM_BRE_RECOVERY_RISK_BLOCK_REASON
  {
   BRE_RECOVERY_RISK_BLOCK_NONE=0,
   BRE_RECOVERY_RISK_BLOCK_PROJECTED_EXCEEDS_MAX=1,
   BRE_RECOVERY_RISK_BLOCK_RISK_DATA_UNSAFE=2,
   BRE_RECOVERY_RISK_BLOCK_RISK_DATA_UNKNOWN=3,
   BRE_RECOVERY_RISK_BLOCK_BASKET_SUSPENDED=4,
   BRE_RECOVERY_RISK_BLOCK_BASKET_LOCKED=5,
   BRE_RECOVERY_RISK_BLOCK_BASKET_CLOSING=6,
   BRE_RECOVERY_RISK_BLOCK_BASKET_FINISHED=7,
   BRE_RECOVERY_RISK_BLOCK_BASKET_RECONCILING=8,
   BRE_RECOVERY_RISK_BLOCK_BASKET_NOT_ACTIVE=9,
   BRE_RECOVERY_RISK_BLOCK_MISSING_BASKET_SL=10,
   BRE_RECOVERY_RISK_BLOCK_STALE_QUOTE=11,
   BRE_RECOVERY_RISK_BLOCK_INVALID_PROPOSED_VOLUME=12,
   BRE_RECOVERY_RISK_BLOCK_UNRESOLVED_PENDING_EXECUTION=13,
   BRE_RECOVERY_RISK_BLOCK_PROFILE_HASH_MISMATCH=14,
   BRE_RECOVERY_RISK_BLOCK_DIRECTION_OR_SYMBOL_CONFLICT=15
  };

class CRecoveryRiskBlockReasonText
  {
public:
   static string     ToString(const ENUM_BRE_RECOVERY_RISK_BLOCK_REASON reason)
     {
      switch(reason)
        {
         case BRE_RECOVERY_RISK_BLOCK_NONE: return "NONE";
         case BRE_RECOVERY_RISK_BLOCK_PROJECTED_EXCEEDS_MAX: return "PROJECTED_EXCEEDS_MAX";
         case BRE_RECOVERY_RISK_BLOCK_RISK_DATA_UNSAFE: return "RISK_DATA_UNSAFE";
         case BRE_RECOVERY_RISK_BLOCK_RISK_DATA_UNKNOWN: return "RISK_DATA_UNKNOWN";
         case BRE_RECOVERY_RISK_BLOCK_BASKET_SUSPENDED: return "BASKET_SUSPENDED";
         case BRE_RECOVERY_RISK_BLOCK_BASKET_LOCKED: return "BASKET_LOCKED";
         case BRE_RECOVERY_RISK_BLOCK_BASKET_CLOSING: return "BASKET_CLOSING";
         case BRE_RECOVERY_RISK_BLOCK_BASKET_FINISHED: return "BASKET_FINISHED";
         case BRE_RECOVERY_RISK_BLOCK_BASKET_RECONCILING: return "BASKET_RECONCILING";
         case BRE_RECOVERY_RISK_BLOCK_BASKET_NOT_ACTIVE: return "BASKET_NOT_ACTIVE";
         case BRE_RECOVERY_RISK_BLOCK_MISSING_BASKET_SL: return "MISSING_BASKET_SL";
         case BRE_RECOVERY_RISK_BLOCK_STALE_QUOTE: return "STALE_QUOTE";
         case BRE_RECOVERY_RISK_BLOCK_INVALID_PROPOSED_VOLUME: return "INVALID_PROPOSED_VOLUME";
         case BRE_RECOVERY_RISK_BLOCK_UNRESOLVED_PENDING_EXECUTION: return "UNRESOLVED_PENDING_EXECUTION";
         case BRE_RECOVERY_RISK_BLOCK_PROFILE_HASH_MISMATCH: return "PROFILE_HASH_MISMATCH";
         case BRE_RECOVERY_RISK_BLOCK_DIRECTION_OR_SYMBOL_CONFLICT: return "DIRECTION_OR_SYMBOL_CONFLICT";
         default: return "UNKNOWN";
        }
     }

   static ENUM_BRE_RECOVERY_RISK_BLOCK_REASON FromRiskViolation(const ENUM_BRE_RISK_VIOLATION_REASON reason)
     {
      switch(reason)
        {
         case BRE_RISK_VIOLATION_PROJECTED_EXCEEDS_MAX: return BRE_RECOVERY_RISK_BLOCK_PROJECTED_EXCEEDS_MAX;
         case BRE_RISK_VIOLATION_BASKET_SUSPENDED: return BRE_RECOVERY_RISK_BLOCK_BASKET_SUSPENDED;
         case BRE_RISK_VIOLATION_BASKET_LOCKED: return BRE_RECOVERY_RISK_BLOCK_BASKET_LOCKED;
         case BRE_RISK_VIOLATION_BASKET_RECONCILING: return BRE_RECOVERY_RISK_BLOCK_BASKET_RECONCILING;
         case BRE_RISK_VIOLATION_RISK_DATA_UNSAFE: return BRE_RECOVERY_RISK_BLOCK_RISK_DATA_UNSAFE;
         case BRE_RISK_VIOLATION_RISK_DATA_UNKNOWN: return BRE_RECOVERY_RISK_BLOCK_RISK_DATA_UNKNOWN;
         case BRE_RISK_VIOLATION_INVALID_MARKET_DATA: return BRE_RECOVERY_RISK_BLOCK_STALE_QUOTE;
         default: return BRE_RECOVERY_RISK_BLOCK_RISK_DATA_UNKNOWN;
        }
     }
  };

#endif
