#ifndef BRE_DOMAIN_RISK_SAFETY_STATUS_MQH
#define BRE_DOMAIN_RISK_SAFETY_STATUS_MQH

enum ENUM_BRE_RISK_SAFETY_STATUS
  {
   BRE_RISK_SAFETY_SAFE=0,
   BRE_RISK_SAFETY_UNKNOWN=1,
   BRE_RISK_SAFETY_UNSAFE=2
  };

#endif
