#ifndef BRE_DOMAIN_RISK_VIOLATION_REASON_MQH
#define BRE_DOMAIN_RISK_VIOLATION_REASON_MQH

enum ENUM_BRE_RISK_VIOLATION_REASON
  {
   BRE_RISK_VIOLATION_NONE=0,
   BRE_RISK_VIOLATION_PROJECTED_EXCEEDS_MAX=1,
   BRE_RISK_VIOLATION_BASKET_SUSPENDED=2,
   BRE_RISK_VIOLATION_BASKET_LOCKED=3,
   BRE_RISK_VIOLATION_BASKET_RECONCILING=4,
   BRE_RISK_VIOLATION_RISK_DATA_UNSAFE=5,
   BRE_RISK_VIOLATION_RISK_DATA_UNKNOWN=6,
   BRE_RISK_VIOLATION_CURRENT_RISK_UNKNOWN=7,
   BRE_RISK_VIOLATION_INVALID_MARKET_DATA=8
  };

class CRiskViolationReasonText
  {
public:
   static string     ToString(const ENUM_BRE_RISK_VIOLATION_REASON reason)
     {
      switch(reason)
        {
         case BRE_RISK_VIOLATION_NONE: return "NONE";
         case BRE_RISK_VIOLATION_PROJECTED_EXCEEDS_MAX: return "PROJECTED_EXCEEDS_MAX";
         case BRE_RISK_VIOLATION_BASKET_SUSPENDED: return "BASKET_SUSPENDED";
         case BRE_RISK_VIOLATION_BASKET_LOCKED: return "BASKET_LOCKED";
         case BRE_RISK_VIOLATION_BASKET_RECONCILING: return "BASKET_RECONCILING";
         case BRE_RISK_VIOLATION_RISK_DATA_UNSAFE: return "RISK_DATA_UNSAFE";
         case BRE_RISK_VIOLATION_RISK_DATA_UNKNOWN: return "RISK_DATA_UNKNOWN";
         case BRE_RISK_VIOLATION_CURRENT_RISK_UNKNOWN: return "CURRENT_RISK_UNKNOWN";
         case BRE_RISK_VIOLATION_INVALID_MARKET_DATA: return "INVALID_MARKET_DATA";
         default: return "UNKNOWN";
        }
     }
  };

#endif
