#ifndef BRE_INF_SIMULATED_EXECUTION_SCENARIO_MQH
#define BRE_INF_SIMULATED_EXECUTION_SCENARIO_MQH

enum ENUM_BRE_SIMULATED_EXECUTION_SCENARIO
  {
   BRE_SIM_EXEC_DEFAULT_ACCEPT_FILL=0,
   BRE_SIM_EXEC_REJECTED=1,
   BRE_SIM_EXEC_TIMEOUT=2,
   BRE_SIM_EXEC_PARTIAL_THEN_FILLED=3,
   BRE_SIM_EXEC_PARTIAL_THEN_REJECTED=4,
   BRE_SIM_EXEC_UNKNOWN=5
  };

#endif
