#ifndef BRE_DOMAIN_BREAK_EVEN_MODIFICATION_FAILURE_REASON_MQH
#define BRE_DOMAIN_BREAK_EVEN_MODIFICATION_FAILURE_REASON_MQH

enum ENUM_BRE_BREAK_EVEN_MODIFICATION_FAILURE_REASON
  {
   BRE_BREAK_EVEN_MOD_FAIL_NONE=0,
   BRE_BREAK_EVEN_MOD_FAIL_DRY_RUN_DISABLED,
   BRE_BREAK_EVEN_MOD_FAIL_CANDIDATE_NOT_DUE,
   BRE_BREAK_EVEN_MOD_FAIL_BASKET_NOT_ACTIVE,
   BRE_BREAK_EVEN_MOD_FAIL_BREAK_EVEN_ALREADY_ACTIVE,
   BRE_BREAK_EVEN_MOD_FAIL_QUOTE_SEQUENCE_MISMATCH,
   BRE_BREAK_EVEN_MOD_FAIL_STALE_QUOTE,
   BRE_BREAK_EVEN_MOD_FAIL_PENDING_EXECUTION,
   BRE_BREAK_EVEN_MOD_FAIL_PROFILE_HASH_MISMATCH,
   BRE_BREAK_EVEN_MOD_FAIL_BASKET_VERSION_MISMATCH,
   BRE_BREAK_EVEN_MOD_FAIL_EMPTY_TICKET_SNAPSHOT,
   BRE_BREAK_EVEN_MOD_FAIL_DUPLICATE_TICKET,
   BRE_BREAK_EVEN_MOD_FAIL_MISSING_TICKET,
   BRE_BREAK_EVEN_MOD_FAIL_SYMBOL_MISMATCH,
   BRE_BREAK_EVEN_MOD_FAIL_DIRECTION_MISMATCH,
   BRE_BREAK_EVEN_MOD_FAIL_INVALID_STOP_PRICE,
   BRE_BREAK_EVEN_MOD_FAIL_UNSAFE_TICKET,
   BRE_BREAK_EVEN_MOD_FAIL_IDEMPOTENCY_DUPLICATE,
   BRE_BREAK_EVEN_MOD_FAIL_ACCOUNT_NOT_ELIGIBLE
  };

class CBreakEvenModificationFailureReasonText
  {
public:
   static string     ToString(const ENUM_BRE_BREAK_EVEN_MODIFICATION_FAILURE_REASON reason)
     {
      switch(reason)
        {
         case BRE_BREAK_EVEN_MOD_FAIL_NONE: return "NONE";
         case BRE_BREAK_EVEN_MOD_FAIL_DRY_RUN_DISABLED: return "DRY_RUN_DISABLED";
         case BRE_BREAK_EVEN_MOD_FAIL_CANDIDATE_NOT_DUE: return "CANDIDATE_NOT_DUE";
         case BRE_BREAK_EVEN_MOD_FAIL_BASKET_NOT_ACTIVE: return "BASKET_NOT_ACTIVE";
         case BRE_BREAK_EVEN_MOD_FAIL_BREAK_EVEN_ALREADY_ACTIVE: return "BREAK_EVEN_ALREADY_ACTIVE";
         case BRE_BREAK_EVEN_MOD_FAIL_QUOTE_SEQUENCE_MISMATCH: return "QUOTE_SEQUENCE_MISMATCH";
         case BRE_BREAK_EVEN_MOD_FAIL_STALE_QUOTE: return "STALE_QUOTE";
         case BRE_BREAK_EVEN_MOD_FAIL_PENDING_EXECUTION: return "PENDING_EXECUTION";
         case BRE_BREAK_EVEN_MOD_FAIL_PROFILE_HASH_MISMATCH: return "PROFILE_HASH_MISMATCH";
         case BRE_BREAK_EVEN_MOD_FAIL_BASKET_VERSION_MISMATCH: return "BASKET_VERSION_MISMATCH";
         case BRE_BREAK_EVEN_MOD_FAIL_EMPTY_TICKET_SNAPSHOT: return "EMPTY_TICKET_SNAPSHOT";
         case BRE_BREAK_EVEN_MOD_FAIL_DUPLICATE_TICKET: return "DUPLICATE_TICKET";
         case BRE_BREAK_EVEN_MOD_FAIL_MISSING_TICKET: return "MISSING_TICKET";
         case BRE_BREAK_EVEN_MOD_FAIL_SYMBOL_MISMATCH: return "SYMBOL_MISMATCH";
         case BRE_BREAK_EVEN_MOD_FAIL_DIRECTION_MISMATCH: return "DIRECTION_MISMATCH";
         case BRE_BREAK_EVEN_MOD_FAIL_INVALID_STOP_PRICE: return "INVALID_STOP_PRICE";
         case BRE_BREAK_EVEN_MOD_FAIL_UNSAFE_TICKET: return "UNSAFE_TICKET";
         case BRE_BREAK_EVEN_MOD_FAIL_IDEMPOTENCY_DUPLICATE: return "IDEMPOTENCY_DUPLICATE";
         case BRE_BREAK_EVEN_MOD_FAIL_ACCOUNT_NOT_ELIGIBLE: return "ACCOUNT_NOT_ELIGIBLE";
         default:
           {
            ENUM_BRE_BREAK_EVEN_MODIFICATION_FAILURE_REASON unreachable=reason;
            return "UNKNOWN";
           }
        }
     }
  };

#endif
