#ifndef BRE_DOMAIN_BREAK_EVEN_CANDIDATE_TRIGGER_TYPE_MQH
#define BRE_DOMAIN_BREAK_EVEN_CANDIDATE_TRIGGER_TYPE_MQH

enum ENUM_BRE_BREAK_EVEN_CANDIDATE_TRIGGER_TYPE
  {
   BRE_BE_CANDIDATE_TRIGGER_NONE=0,
   BRE_BE_CANDIDATE_TRIGGER_FLOATING_PROFIT_MONEY,
   BRE_BE_CANDIDATE_TRIGGER_FLOATING_PROFIT_PCT_TARGET_RISK,
   BRE_BE_CANDIDATE_TRIGGER_REALIZED_PROFIT_MONEY,
   BRE_BE_CANDIDATE_TRIGGER_PROFIT_LEVEL_COMPLETED,
   BRE_BE_CANDIDATE_TRIGGER_RISK_REDUCTION_COMPLETED,
   BRE_BE_CANDIDATE_TRIGGER_MANUAL_EVENT
  };

class CBreakEvenCandidateTriggerTypeText
  {
public:
   static string     ToString(const ENUM_BRE_BREAK_EVEN_CANDIDATE_TRIGGER_TYPE triggerType)
     {
      switch(triggerType)
        {
         case BRE_BE_CANDIDATE_TRIGGER_FLOATING_PROFIT_MONEY: return "FLOATING_PROFIT_MONEY";
         case BRE_BE_CANDIDATE_TRIGGER_FLOATING_PROFIT_PCT_TARGET_RISK: return "FLOATING_PROFIT_PCT_TARGET_RISK";
         case BRE_BE_CANDIDATE_TRIGGER_REALIZED_PROFIT_MONEY: return "REALIZED_PROFIT_MONEY";
         case BRE_BE_CANDIDATE_TRIGGER_PROFIT_LEVEL_COMPLETED: return "PROFIT_LEVEL_COMPLETED";
         case BRE_BE_CANDIDATE_TRIGGER_RISK_REDUCTION_COMPLETED: return "RISK_REDUCTION_COMPLETED";
         case BRE_BE_CANDIDATE_TRIGGER_MANUAL_EVENT: return "MANUAL_EVENT";
         default: return "NONE";
        }
     }
  };

#endif
