#ifndef BRE_DOMAIN_BREAK_EVEN_CANDIDATE_STATUS_MQH
#define BRE_DOMAIN_BREAK_EVEN_CANDIDATE_STATUS_MQH

enum ENUM_BRE_BREAK_EVEN_CANDIDATE_STATUS
  {
   BRE_BREAK_EVEN_CANDIDATE_NOT_REACHED=0,
   BRE_BREAK_EVEN_CANDIDATE_DUE,
   BRE_BREAK_EVEN_CANDIDATE_ALREADY_ACTIVATED,
   BRE_BREAK_EVEN_CANDIDATE_BLOCKED_BY_PENDING_EXECUTION,
   BRE_BREAK_EVEN_CANDIDATE_BLOCKED_BY_SAFETY,
   BRE_BREAK_EVEN_CANDIDATE_INVALID_PROFILE,
   BRE_BREAK_EVEN_CANDIDATE_INVALID_MARKET_CONTEXT,
   BRE_BREAK_EVEN_CANDIDATE_INVALID_STOP_PRICE,
   BRE_BREAK_EVEN_CANDIDATE_NOT_IMPLEMENTED
  };

class CBreakEvenCandidateStatusText
  {
public:
   static string     ToString(const ENUM_BRE_BREAK_EVEN_CANDIDATE_STATUS status)
     {
      switch(status)
        {
         case BRE_BREAK_EVEN_CANDIDATE_NOT_REACHED: return "NOT_REACHED";
         case BRE_BREAK_EVEN_CANDIDATE_DUE: return "DUE";
         case BRE_BREAK_EVEN_CANDIDATE_ALREADY_ACTIVATED: return "ALREADY_ACTIVATED";
         case BRE_BREAK_EVEN_CANDIDATE_BLOCKED_BY_PENDING_EXECUTION: return "BLOCKED_BY_PENDING_EXECUTION";
         case BRE_BREAK_EVEN_CANDIDATE_BLOCKED_BY_SAFETY: return "BLOCKED_BY_SAFETY";
         case BRE_BREAK_EVEN_CANDIDATE_INVALID_PROFILE: return "INVALID_PROFILE";
         case BRE_BREAK_EVEN_CANDIDATE_INVALID_MARKET_CONTEXT: return "INVALID_MARKET_CONTEXT";
         case BRE_BREAK_EVEN_CANDIDATE_INVALID_STOP_PRICE: return "INVALID_STOP_PRICE";
         case BRE_BREAK_EVEN_CANDIDATE_NOT_IMPLEMENTED: return "NOT_IMPLEMENTED";
         default:
           {
            ENUM_BRE_BREAK_EVEN_CANDIDATE_STATUS unreachable=status;
            return "UNKNOWN";
           }
        }
     }
  };

#endif
