#ifndef BRE_DOMAIN_BREAK_EVEN_REASON_MQH
#define BRE_DOMAIN_BREAK_EVEN_REASON_MQH

enum ENUM_BRE_BREAK_EVEN_REASON
  {
   BRE_BREAK_EVEN_REASON_NONE=0,
   BRE_BREAK_EVEN_REASON_TRIGGER_NOT_SATISFIED,
   BRE_BREAK_EVEN_REASON_RULE_ALREADY_EXECUTED,
   BRE_BREAK_EVEN_REASON_BREAK_EVEN_ALREADY_ACTIVE,
   BRE_BREAK_EVEN_REASON_BASKET_NOT_ACTIVE,
   BRE_BREAK_EVEN_REASON_BASKET_LOCKED,
   BRE_BREAK_EVEN_REASON_PENDING_EXECUTION,
   BRE_BREAK_EVEN_REASON_STALE_QUOTE,
   BRE_BREAK_EVEN_REASON_INVALID_SESSION,
   BRE_BREAK_EVEN_REASON_INVALID_PROFILE,
   BRE_BREAK_EVEN_REASON_UNSUPPORTED_TRIGGER,
   BRE_BREAK_EVEN_REASON_DUPLICATE_QUOTE_SEQUENCE,
   BRE_BREAK_EVEN_REASON_NO_OPEN_POSITIONS,
   BRE_BREAK_EVEN_REASON_INVALID_WEIGHTED_ENTRY,
   BRE_BREAK_EVEN_REASON_UNRELIABLE_RISK_DATA,
   BRE_BREAK_EVEN_REASON_NO_SL_ACTION,
   BRE_BREAK_EVEN_REASON_STOP_LEVEL_VIOLATION,
   BRE_BREAK_EVEN_REASON_FREEZE_LEVEL_VIOLATION,
   BRE_BREAK_EVEN_REASON_SYMBOL_SIDE_MISMATCH
  };

class CBreakEvenReasonText
  {
public:
   static string     ToString(const ENUM_BRE_BREAK_EVEN_REASON reason)
     {
      switch(reason)
        {
         case BRE_BREAK_EVEN_REASON_NONE: return "NONE";
         case BRE_BREAK_EVEN_REASON_TRIGGER_NOT_SATISFIED: return "TRIGGER_NOT_SATISFIED";
         case BRE_BREAK_EVEN_REASON_RULE_ALREADY_EXECUTED: return "RULE_ALREADY_EXECUTED";
         case BRE_BREAK_EVEN_REASON_BREAK_EVEN_ALREADY_ACTIVE: return "BREAK_EVEN_ALREADY_ACTIVE";
         case BRE_BREAK_EVEN_REASON_BASKET_NOT_ACTIVE: return "BASKET_NOT_ACTIVE";
         case BRE_BREAK_EVEN_REASON_BASKET_LOCKED: return "BASKET_LOCKED";
         case BRE_BREAK_EVEN_REASON_PENDING_EXECUTION: return "PENDING_EXECUTION";
         case BRE_BREAK_EVEN_REASON_STALE_QUOTE: return "STALE_QUOTE";
         case BRE_BREAK_EVEN_REASON_INVALID_SESSION: return "INVALID_SESSION";
         case BRE_BREAK_EVEN_REASON_INVALID_PROFILE: return "INVALID_PROFILE";
         case BRE_BREAK_EVEN_REASON_UNSUPPORTED_TRIGGER: return "UNSUPPORTED_TRIGGER";
         case BRE_BREAK_EVEN_REASON_DUPLICATE_QUOTE_SEQUENCE: return "DUPLICATE_QUOTE_SEQUENCE";
         case BRE_BREAK_EVEN_REASON_NO_OPEN_POSITIONS: return "NO_OPEN_POSITIONS";
         case BRE_BREAK_EVEN_REASON_INVALID_WEIGHTED_ENTRY: return "INVALID_WEIGHTED_ENTRY";
         case BRE_BREAK_EVEN_REASON_UNRELIABLE_RISK_DATA: return "UNRELIABLE_RISK_DATA";
         case BRE_BREAK_EVEN_REASON_NO_SL_ACTION: return "NO_SL_ACTION";
         case BRE_BREAK_EVEN_REASON_STOP_LEVEL_VIOLATION: return "STOP_LEVEL_VIOLATION";
         case BRE_BREAK_EVEN_REASON_FREEZE_LEVEL_VIOLATION: return "FREEZE_LEVEL_VIOLATION";
         case BRE_BREAK_EVEN_REASON_SYMBOL_SIDE_MISMATCH: return "SYMBOL_SIDE_MISMATCH";
         default:
           {
            ENUM_BRE_BREAK_EVEN_REASON unreachable=reason;
            return "UNKNOWN";
           }
        }
     }
  };

#endif
