#ifndef BRE_DOMAIN_PROFIT_LEVEL_CLOSE_CANDIDATE_STATUS_MQH
#define BRE_DOMAIN_PROFIT_LEVEL_CLOSE_CANDIDATE_STATUS_MQH

enum ENUM_BRE_PROFIT_LEVEL_CLOSE_CANDIDATE_STATUS
  {
   BRE_PROFIT_LEVEL_CLOSE_NOT_REACHED=0,
   BRE_PROFIT_LEVEL_CLOSE_DUE,
   BRE_PROFIT_LEVEL_CLOSE_ALREADY_COMPLETED,
   BRE_PROFIT_LEVEL_CLOSE_BLOCKED_BY_PENDING_EXECUTION,
   BRE_PROFIT_LEVEL_CLOSE_BLOCKED_BY_SAFETY,
   BRE_PROFIT_LEVEL_CLOSE_INVALID_PROFILE,
   BRE_PROFIT_LEVEL_CLOSE_INVALID_MARKET_CONTEXT,
   BRE_PROFIT_LEVEL_CLOSE_INVALID_CLOSE_PLAN,
   BRE_PROFIT_LEVEL_CLOSE_NOT_IMPLEMENTED
  };

class CProfitLevelCloseCandidateStatusText
  {
public:
   static string     ToString(const ENUM_BRE_PROFIT_LEVEL_CLOSE_CANDIDATE_STATUS status)
     {
      switch(status)
        {
         case BRE_PROFIT_LEVEL_CLOSE_NOT_REACHED: return "NOT_REACHED";
         case BRE_PROFIT_LEVEL_CLOSE_DUE: return "DUE";
         case BRE_PROFIT_LEVEL_CLOSE_ALREADY_COMPLETED: return "ALREADY_COMPLETED";
         case BRE_PROFIT_LEVEL_CLOSE_BLOCKED_BY_PENDING_EXECUTION: return "BLOCKED_BY_PENDING_EXECUTION";
         case BRE_PROFIT_LEVEL_CLOSE_BLOCKED_BY_SAFETY: return "BLOCKED_BY_SAFETY";
         case BRE_PROFIT_LEVEL_CLOSE_INVALID_PROFILE: return "INVALID_PROFILE";
         case BRE_PROFIT_LEVEL_CLOSE_INVALID_MARKET_CONTEXT: return "INVALID_MARKET_CONTEXT";
         case BRE_PROFIT_LEVEL_CLOSE_INVALID_CLOSE_PLAN: return "INVALID_CLOSE_PLAN";
         case BRE_PROFIT_LEVEL_CLOSE_NOT_IMPLEMENTED: return "NOT_IMPLEMENTED";
         default:
           {
            ENUM_BRE_PROFIT_LEVEL_CLOSE_CANDIDATE_STATUS unreachable=status;
            return "UNKNOWN";
           }
        }
     }
  };

#endif
