#ifndef BRE_DOMAIN_PROFIT_LEVEL_TRIGGER_TYPE_MQH
#define BRE_DOMAIN_PROFIT_LEVEL_TRIGGER_TYPE_MQH

enum ENUM_BRE_PROFIT_LEVEL_TRIGGER_TYPE
  {
   BRE_PROFIT_LEVEL_TRIGGER_INFER_FROM_SOURCE=0,
   BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_MONEY,
   BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_PCT_TARGET_RISK,
   BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_PCT_EQUITY,
   BRE_PROFIT_LEVEL_TRIGGER_STRATEGY_PRICE_LEVEL,
   BRE_PROFIT_LEVEL_TRIGGER_FUTURE_PLACEHOLDER
  };

class CProfitLevelTriggerTypeHelper
  {
public:
   static string     ToString(const ENUM_BRE_PROFIT_LEVEL_TRIGGER_TYPE type)
     {
      switch(type)
        {
         case BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_MONEY: return "FLOATING_PROFIT_MONEY";
         case BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_PCT_TARGET_RISK: return "FLOATING_PROFIT_PCT_TARGET_RISK";
         case BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_PCT_EQUITY: return "FLOATING_PROFIT_PCT_EQUITY";
         case BRE_PROFIT_LEVEL_TRIGGER_STRATEGY_PRICE_LEVEL: return "STRATEGY_PRICE_LEVEL";
         case BRE_PROFIT_LEVEL_TRIGGER_FUTURE_PLACEHOLDER: return "FUTURE_PLACEHOLDER";
         default: return "INFER_FROM_SOURCE";
        }
     }

   static ENUM_BRE_PROFIT_LEVEL_TRIGGER_TYPE FromString(const string value)
     {
      if(value=="FLOATING_PROFIT_MONEY")
         return BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_MONEY;
      if(value=="FLOATING_PROFIT_PCT_TARGET_RISK")
         return BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_PCT_TARGET_RISK;
      if(value=="FLOATING_PROFIT_PCT_EQUITY")
         return BRE_PROFIT_LEVEL_TRIGGER_FLOATING_PROFIT_PCT_EQUITY;
      if(value=="STRATEGY_PRICE_LEVEL")
         return BRE_PROFIT_LEVEL_TRIGGER_STRATEGY_PRICE_LEVEL;
      if(value=="FUTURE_PLACEHOLDER")
         return BRE_PROFIT_LEVEL_TRIGGER_FUTURE_PLACEHOLDER;
      return BRE_PROFIT_LEVEL_TRIGGER_INFER_FROM_SOURCE;
     }
  };

#endif
