#ifndef BRE_DOMAIN_PROFIT_LEVEL_CLOSE_REASON_MQH
#define BRE_DOMAIN_PROFIT_LEVEL_CLOSE_REASON_MQH

enum ENUM_BRE_PROFIT_LEVEL_CLOSE_REASON
  {
   BRE_PROFIT_LEVEL_CLOSE_REASON_NONE=0,
   BRE_PROFIT_LEVEL_CLOSE_REASON_TRIGGER_NOT_SATISFIED,
   BRE_PROFIT_LEVEL_CLOSE_REASON_LEVEL_ALREADY_COMPLETED,
   BRE_PROFIT_LEVEL_CLOSE_REASON_NEGATIVE_FLOATING_PROFIT,
   BRE_PROFIT_LEVEL_CLOSE_REASON_BASKET_NOT_ACTIVE,
   BRE_PROFIT_LEVEL_CLOSE_REASON_BASKET_LOCKED,
   BRE_PROFIT_LEVEL_CLOSE_REASON_PENDING_EXECUTION,
   BRE_PROFIT_LEVEL_CLOSE_REASON_STALE_QUOTE,
   BRE_PROFIT_LEVEL_CLOSE_REASON_INVALID_SESSION,
   BRE_PROFIT_LEVEL_CLOSE_REASON_INVALID_PROFILE,
   BRE_PROFIT_LEVEL_CLOSE_REASON_UNSUPPORTED_TRIGGER,
   BRE_PROFIT_LEVEL_CLOSE_REASON_DUPLICATE_QUOTE_SEQUENCE,
   BRE_PROFIT_LEVEL_CLOSE_REASON_NO_OPEN_POSITIONS,
   BRE_PROFIT_LEVEL_CLOSE_REASON_VOLUME_PLAN_FAILED,
   BRE_PROFIT_LEVEL_CLOSE_REASON_BROKER_MIN_VOLUME_OVERRUN,
   BRE_PROFIT_LEVEL_CLOSE_REASON_SYMBOL_SIDE_MISMATCH
  };

class CProfitLevelCloseReasonText
  {
public:
   static string     ToString(const ENUM_BRE_PROFIT_LEVEL_CLOSE_REASON reason)
     {
      switch(reason)
        {
         case BRE_PROFIT_LEVEL_CLOSE_REASON_NONE: return "NONE";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_TRIGGER_NOT_SATISFIED: return "TRIGGER_NOT_SATISFIED";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_LEVEL_ALREADY_COMPLETED: return "LEVEL_ALREADY_COMPLETED";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_NEGATIVE_FLOATING_PROFIT: return "NEGATIVE_FLOATING_PROFIT";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_BASKET_NOT_ACTIVE: return "BASKET_NOT_ACTIVE";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_BASKET_LOCKED: return "BASKET_LOCKED";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_PENDING_EXECUTION: return "PENDING_EXECUTION";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_STALE_QUOTE: return "STALE_QUOTE";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_INVALID_SESSION: return "INVALID_SESSION";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_INVALID_PROFILE: return "INVALID_PROFILE";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_UNSUPPORTED_TRIGGER: return "UNSUPPORTED_TRIGGER";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_DUPLICATE_QUOTE_SEQUENCE: return "DUPLICATE_QUOTE_SEQUENCE";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_NO_OPEN_POSITIONS: return "NO_OPEN_POSITIONS";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_VOLUME_PLAN_FAILED: return "VOLUME_PLAN_FAILED";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_BROKER_MIN_VOLUME_OVERRUN: return "BROKER_MIN_VOLUME_OVERRUN";
         case BRE_PROFIT_LEVEL_CLOSE_REASON_SYMBOL_SIDE_MISMATCH: return "SYMBOL_SIDE_MISMATCH";
         default:
           {
            ENUM_BRE_PROFIT_LEVEL_CLOSE_REASON unreachable=reason;
            return "UNKNOWN";
           }
        }
     }
  };

#endif
