#ifndef BRE_DOMAIN_RECOVERY_CANDIDATE_REASON_MQH
#define BRE_DOMAIN_RECOVERY_CANDIDATE_REASON_MQH

enum ENUM_BRE_RECOVERY_CANDIDATE_REASON
  {
   BRE_RECOVERY_CANDIDATE_REASON_NONE=0,
   BRE_RECOVERY_CANDIDATE_REASON_FAVORABLE_MOVEMENT,
   BRE_RECOVERY_CANDIDATE_REASON_INSUFFICIENT_ADVERSE_MOVE,
   BRE_RECOVERY_CANDIDATE_REASON_RECOVERY_DISABLED,
   BRE_RECOVERY_CANDIDATE_REASON_RECOVERY_NOT_ACTIVE,
   BRE_RECOVERY_CANDIDATE_REASON_BREAK_EVEN_DISABLED,
   BRE_RECOVERY_CANDIDATE_REASON_BASKET_NOT_ACTIVE,
   BRE_RECOVERY_CANDIDATE_REASON_STEP_LIMIT_REACHED,
   BRE_RECOVERY_CANDIDATE_REASON_OUTSIDE_EXECUTION_ZONE,
   BRE_RECOVERY_CANDIDATE_REASON_PENDING_EXECUTION,
   BRE_RECOVERY_CANDIDATE_REASON_STALE_QUOTE,
   BRE_RECOVERY_CANDIDATE_REASON_INVALID_SESSION,
   BRE_RECOVERY_CANDIDATE_REASON_INVALID_VOLUME,
   BRE_RECOVERY_CANDIDATE_REASON_INVALID_PROFILE,
   BRE_RECOVERY_CANDIDATE_REASON_SYMBOL_SIDE_MISMATCH,
   BRE_RECOVERY_CANDIDATE_REASON_DUPLICATE_QUOTE_SEQUENCE,
   BRE_RECOVERY_CANDIDATE_REASON_PROJECTED_RISK_EXCEEDED,
   BRE_RECOVERY_CANDIDATE_REASON_UNSUPPORTED_ALGORITHM,
   BRE_RECOVERY_CANDIDATE_REASON_RISK_BUDGET_NOT_IMPLEMENTED
  };

class CRecoveryCandidateReasonText
  {
public:
   static string     ToString(const ENUM_BRE_RECOVERY_CANDIDATE_REASON reason)
     {
      switch(reason)
        {
         case BRE_RECOVERY_CANDIDATE_REASON_NONE: return "NONE";
         case BRE_RECOVERY_CANDIDATE_REASON_FAVORABLE_MOVEMENT: return "FAVORABLE_MOVEMENT";
         case BRE_RECOVERY_CANDIDATE_REASON_INSUFFICIENT_ADVERSE_MOVE: return "INSUFFICIENT_ADVERSE_MOVE";
         case BRE_RECOVERY_CANDIDATE_REASON_RECOVERY_DISABLED: return "RECOVERY_DISABLED";
         case BRE_RECOVERY_CANDIDATE_REASON_RECOVERY_NOT_ACTIVE: return "RECOVERY_NOT_ACTIVE";
         case BRE_RECOVERY_CANDIDATE_REASON_BREAK_EVEN_DISABLED: return "BREAK_EVEN_DISABLED";
         case BRE_RECOVERY_CANDIDATE_REASON_BASKET_NOT_ACTIVE: return "BASKET_NOT_ACTIVE";
         case BRE_RECOVERY_CANDIDATE_REASON_STEP_LIMIT_REACHED: return "STEP_LIMIT_REACHED";
         case BRE_RECOVERY_CANDIDATE_REASON_OUTSIDE_EXECUTION_ZONE: return "OUTSIDE_EXECUTION_ZONE";
         case BRE_RECOVERY_CANDIDATE_REASON_PENDING_EXECUTION: return "PENDING_EXECUTION";
         case BRE_RECOVERY_CANDIDATE_REASON_STALE_QUOTE: return "STALE_QUOTE";
         case BRE_RECOVERY_CANDIDATE_REASON_INVALID_SESSION: return "INVALID_SESSION";
         case BRE_RECOVERY_CANDIDATE_REASON_INVALID_VOLUME: return "INVALID_VOLUME";
         case BRE_RECOVERY_CANDIDATE_REASON_INVALID_PROFILE: return "INVALID_PROFILE";
         case BRE_RECOVERY_CANDIDATE_REASON_SYMBOL_SIDE_MISMATCH: return "SYMBOL_SIDE_MISMATCH";
         case BRE_RECOVERY_CANDIDATE_REASON_DUPLICATE_QUOTE_SEQUENCE: return "DUPLICATE_QUOTE_SEQUENCE";
         case BRE_RECOVERY_CANDIDATE_REASON_PROJECTED_RISK_EXCEEDED: return "PROJECTED_RISK_EXCEEDED";
         case BRE_RECOVERY_CANDIDATE_REASON_UNSUPPORTED_ALGORITHM: return "UNSUPPORTED_ALGORITHM";
         case BRE_RECOVERY_CANDIDATE_REASON_RISK_BUDGET_NOT_IMPLEMENTED: return "RISK_BUDGET_NOT_IMPLEMENTED";
         default:
           {
            ENUM_BRE_RECOVERY_CANDIDATE_REASON unreachable=reason;
            return "UNKNOWN";
           }
        }
     }
  };

#endif
