#ifndef BRE_DOMAIN_RECOVERY_CANDIDATE_STATUS_MQH
#define BRE_DOMAIN_RECOVERY_CANDIDATE_STATUS_MQH

enum ENUM_BRE_RECOVERY_CANDIDATE_STATUS
  {
   BRE_RECOVERY_CANDIDATE_NOT_DUE=0,
   BRE_RECOVERY_CANDIDATE_DUE,
   BRE_RECOVERY_CANDIDATE_BLOCKED_BY_ZONE,
   BRE_RECOVERY_CANDIDATE_BLOCKED_BY_STEP_LIMIT,
   BRE_RECOVERY_CANDIDATE_BLOCKED_BY_PENDING_EXECUTION,
   BRE_RECOVERY_CANDIDATE_BLOCKED_BY_RISK,
   BRE_RECOVERY_CANDIDATE_BLOCKED_BY_SAFETY,
   BRE_RECOVERY_CANDIDATE_INVALID_PROFILE,
   BRE_RECOVERY_CANDIDATE_INVALID_MARKET_CONTEXT
  };

class CRecoveryCandidateStatusText
  {
public:
   static string     ToString(const ENUM_BRE_RECOVERY_CANDIDATE_STATUS status)
     {
      switch(status)
        {
         case BRE_RECOVERY_CANDIDATE_NOT_DUE: return "NOT_DUE";
         case BRE_RECOVERY_CANDIDATE_DUE: return "DUE";
         case BRE_RECOVERY_CANDIDATE_BLOCKED_BY_ZONE: return "BLOCKED_BY_ZONE";
         case BRE_RECOVERY_CANDIDATE_BLOCKED_BY_STEP_LIMIT: return "BLOCKED_BY_STEP_LIMIT";
         case BRE_RECOVERY_CANDIDATE_BLOCKED_BY_PENDING_EXECUTION: return "BLOCKED_BY_PENDING_EXECUTION";
         case BRE_RECOVERY_CANDIDATE_BLOCKED_BY_RISK: return "BLOCKED_BY_RISK";
         case BRE_RECOVERY_CANDIDATE_BLOCKED_BY_SAFETY: return "BLOCKED_BY_SAFETY";
         case BRE_RECOVERY_CANDIDATE_INVALID_PROFILE: return "INVALID_PROFILE";
         case BRE_RECOVERY_CANDIDATE_INVALID_MARKET_CONTEXT: return "INVALID_MARKET_CONTEXT";
         default:
           {
            ENUM_BRE_RECOVERY_CANDIDATE_STATUS unreachable=status;
            return "UNKNOWN";
           }
        }
     }

   static bool       IsAllowedForCommand(const ENUM_BRE_RECOVERY_CANDIDATE_STATUS status)
     {
      return status==BRE_RECOVERY_CANDIDATE_DUE;
     }
  };

#endif
