#ifndef BASKET_RECOVERY_DOMAIN_STRATEGY_DECISION_TYPE_MQH
#define BASKET_RECOVERY_DOMAIN_STRATEGY_DECISION_TYPE_MQH

enum ENUM_BRE_STRATEGY_DECISION_TYPE
  {
   BRE_STRATEGY_DECISION_NONE=0,
   BRE_STRATEGY_DECISION_OPEN_RECOVERY,
   BRE_STRATEGY_DECISION_CLOSE_POSITIONS,
   BRE_STRATEGY_DECISION_MOVE_BREAK_EVEN,
   BRE_STRATEGY_DECISION_DISABLE_RECOVERY,
   BRE_STRATEGY_DECISION_REDUCE_RISK,
   BRE_STRATEGY_DECISION_NO_ACTION
  };

#endif
