#ifndef BRE_DOMAIN_FAST_TRACK_SIGNAL_TYPES_MQH
#define BRE_DOMAIN_FAST_TRACK_SIGNAL_TYPES_MQH

enum ENUM_BRE_FAST_TRACK_SIGNAL_KIND
  {
   BRE_FAST_TRACK_SIGNAL_NONE=0,
   BRE_FAST_TRACK_SIGNAL_SEED,
   BRE_FAST_TRACK_SIGNAL_DETAILS
  };

enum ENUM_BRE_FAST_TRACK_PARSE_FAILURE_REASON
  {
   BRE_FAST_TRACK_PARSE_OK=0,
   BRE_FAST_TRACK_PARSE_EMPTY_MESSAGE,
   BRE_FAST_TRACK_PARSE_UNKNOWN_SYMBOL,
   BRE_FAST_TRACK_PARSE_UNKNOWN_DIRECTION,
   BRE_FAST_TRACK_PARSE_MISSING_ENTRY_RANGE,
   BRE_FAST_TRACK_PARSE_MISSING_STOP_LOSS,
   BRE_FAST_TRACK_PARSE_MISSING_TAKE_PROFIT,
   BRE_FAST_TRACK_PARSE_INVALID_NUMBER,
   BRE_FAST_TRACK_PARSE_STOP_LOSS_OUT_OF_RANGE,
   BRE_FAST_TRACK_PARSE_TAKE_PROFIT_OUT_OF_RANGE,
   BRE_FAST_TRACK_PARSE_TAKE_PROFIT_NOT_ORDERED,
   BRE_FAST_TRACK_PARSE_INVALID_SEED_FORMAT
  };

enum ENUM_BRE_FAST_TRACK_DETAILS_MATCH_RESULT
  {
   BRE_FAST_TRACK_MATCH_NONE=0,
   BRE_FAST_TRACK_MATCH_OK,
   BRE_FAST_TRACK_MATCH_NO_CANDIDATE,
   BRE_FAST_TRACK_MATCH_AMBIGUOUS_DETAILS_MATCH,
   BRE_FAST_TRACK_MATCH_EXPIRED_SEED,
   BRE_FAST_TRACK_MATCH_SYMBOL_MISMATCH,
   BRE_FAST_TRACK_MATCH_DIRECTION_MISMATCH
  };

enum ENUM_BRE_FAST_TRACK_ORDER_CLASSIFICATION
  {
   BRE_FAST_TRACK_ORDER_NONE=0,
   BRE_FAST_TRACK_ORDER_RANGE_ADD,
   BRE_FAST_TRACK_ORDER_RECOVERY
  };

enum ENUM_BRE_FAST_TRACK_RECOVERY_DECISION_RESULT
  {
   BRE_FAST_TRACK_RECOVERY_NO_ACTION=0,
   BRE_FAST_TRACK_RECOVERY_ALLOW_RANGE_ADD,
   BRE_FAST_TRACK_RECOVERY_ALLOW_RECOVERY,
   BRE_FAST_TRACK_RECOVERY_BLOCK_MAX_RISK,
   BRE_FAST_TRACK_RECOVERY_BLOCK_MAX_RISK_LOCK
  };

enum ENUM_BRE_FAST_TRACK_DERISK_DECISION_RESULT
  {
   BRE_FAST_TRACK_DERISK_NO_ACTION=0,
   BRE_FAST_TRACK_DERISK_REQUIRED,
   BRE_FAST_TRACK_DERISK_BE_AT_TP1,
   BRE_FAST_TRACK_DERISK_BE_AT_TP2
  };

class CFastTrackSignalTypeText
  {
public:
   static string     ParseFailureToString(const ENUM_BRE_FAST_TRACK_PARSE_FAILURE_REASON reason)
     {
      switch(reason)
        {
         case BRE_FAST_TRACK_PARSE_OK: return "OK";
         case BRE_FAST_TRACK_PARSE_EMPTY_MESSAGE: return "EMPTY_MESSAGE";
         case BRE_FAST_TRACK_PARSE_UNKNOWN_SYMBOL: return "UNKNOWN_SYMBOL";
         case BRE_FAST_TRACK_PARSE_UNKNOWN_DIRECTION: return "UNKNOWN_DIRECTION";
         case BRE_FAST_TRACK_PARSE_MISSING_ENTRY_RANGE: return "MISSING_ENTRY_RANGE";
         case BRE_FAST_TRACK_PARSE_MISSING_STOP_LOSS: return "MISSING_STOP_LOSS";
         case BRE_FAST_TRACK_PARSE_MISSING_TAKE_PROFIT: return "MISSING_TAKE_PROFIT";
         case BRE_FAST_TRACK_PARSE_INVALID_NUMBER: return "INVALID_NUMBER";
         case BRE_FAST_TRACK_PARSE_STOP_LOSS_OUT_OF_RANGE: return "STOP_LOSS_OUT_OF_RANGE";
         case BRE_FAST_TRACK_PARSE_TAKE_PROFIT_OUT_OF_RANGE: return "TAKE_PROFIT_OUT_OF_RANGE";
         case BRE_FAST_TRACK_PARSE_TAKE_PROFIT_NOT_ORDERED: return "TAKE_PROFIT_NOT_ORDERED";
         case BRE_FAST_TRACK_PARSE_INVALID_SEED_FORMAT: return "INVALID_SEED_FORMAT";
         default: return "UNKNOWN";
        }
     }

   static string     MatchResultToString(const ENUM_BRE_FAST_TRACK_DETAILS_MATCH_RESULT result)
     {
      switch(result)
        {
         case BRE_FAST_TRACK_MATCH_OK: return "OK";
         case BRE_FAST_TRACK_MATCH_NO_CANDIDATE: return "NO_CANDIDATE";
         case BRE_FAST_TRACK_MATCH_AMBIGUOUS_DETAILS_MATCH: return "AMBIGUOUS_DETAILS_MATCH";
         case BRE_FAST_TRACK_MATCH_EXPIRED_SEED: return "EXPIRED_SEED";
         case BRE_FAST_TRACK_MATCH_SYMBOL_MISMATCH: return "SYMBOL_MISMATCH";
         case BRE_FAST_TRACK_MATCH_DIRECTION_MISMATCH: return "DIRECTION_MISMATCH";
         default: return "NONE";
        }
     }

   static string     RecoveryDecisionToString(const ENUM_BRE_FAST_TRACK_RECOVERY_DECISION_RESULT result)
     {
      switch(result)
        {
         case BRE_FAST_TRACK_RECOVERY_ALLOW_RANGE_ADD: return "ALLOW_RANGE_ADD";
         case BRE_FAST_TRACK_RECOVERY_ALLOW_RECOVERY: return "ALLOW_RECOVERY";
         case BRE_FAST_TRACK_RECOVERY_BLOCK_MAX_RISK: return "BLOCK_MAX_RISK";
         case BRE_FAST_TRACK_RECOVERY_BLOCK_MAX_RISK_LOCK: return "BLOCK_MAX_RISK_LOCK";
         default: return "NO_ACTION";
        }
     }

   static string     DeRiskDecisionToString(const ENUM_BRE_FAST_TRACK_DERISK_DECISION_RESULT result)
     {
      switch(result)
        {
         case BRE_FAST_TRACK_DERISK_REQUIRED: return "DE_RISK_REQUIRED";
         case BRE_FAST_TRACK_DERISK_BE_AT_TP1: return "BE_AT_TP1";
         case BRE_FAST_TRACK_DERISK_BE_AT_TP2: return "BE_AT_TP2";
         default: return "NO_ACTION";
        }
     }
  };

#endif
