#ifndef BRE_DOMAIN_ACCOUNT_EXECUTION_ELIGIBILITY_CLASSIFICATION_MQH
#define BRE_DOMAIN_ACCOUNT_EXECUTION_ELIGIBILITY_CLASSIFICATION_MQH

enum ENUM_BRE_ACCOUNT_EXECUTION_ELIGIBILITY_CLASSIFICATION
  {
   BRE_ACCOUNT_ELIGIBILITY_UNKNOWN=0,
   BRE_ACCOUNT_ELIGIBILITY_DEMO=1,
   BRE_ACCOUNT_ELIGIBILITY_REAL=2
  };

inline string AccountExecutionEligibilityClassificationLabel(const ENUM_BRE_ACCOUNT_EXECUTION_ELIGIBILITY_CLASSIFICATION value)
  {
   switch(value)
     {
      case BRE_ACCOUNT_ELIGIBILITY_DEMO: return "DEMO";
      case BRE_ACCOUNT_ELIGIBILITY_REAL: return "REAL";
      default: return "UNKNOWN";
     }
  }

#endif
