#ifndef BRE_DOMAIN_EXECUTION_AUTHORIZATION_STATUS_MQH
#define BRE_DOMAIN_EXECUTION_AUTHORIZATION_STATUS_MQH

enum ENUM_BRE_EXECUTION_AUTHORIZATION_STATUS
  {
   BRE_AUTH_STATUS_NONE=0,
   BRE_AUTH_STATUS_REJECTED=1,
   BRE_AUTH_STATUS_AUTHORIZED_FOR_FUTURE_SUBMISSION=2,
   BRE_AUTH_STATUS_CONSUMED=3,
   BRE_AUTH_STATUS_EXPIRED=4
  };

inline string ExecutionAuthorizationStatusLabel(const ENUM_BRE_EXECUTION_AUTHORIZATION_STATUS status)
  {
   switch(status)
     {
      case BRE_AUTH_STATUS_REJECTED: return "REJECTED";
      case BRE_AUTH_STATUS_AUTHORIZED_FOR_FUTURE_SUBMISSION: return "AUTHORIZED_FOR_FUTURE_SUBMISSION";
      case BRE_AUTH_STATUS_CONSUMED: return "CONSUMED";
      case BRE_AUTH_STATUS_EXPIRED: return "EXPIRED";
      default: return "NONE";
     }
  }

#endif
