#ifndef BRE_DOMAIN_EXECUTION_AUTHORIZATION_SCOPE_MQH
#define BRE_DOMAIN_EXECUTION_AUTHORIZATION_SCOPE_MQH

enum ENUM_BRE_EXECUTION_AUTHORIZATION_SCOPE
  {
   BRE_AUTH_SCOPE_NONE=0,
   BRE_AUTH_SCOPE_DRY_RUN_ONLY=1,
   BRE_AUTH_SCOPE_SIMULATED_ONLY=2,
   BRE_AUTH_SCOPE_DEMO_SINGLE_REQUEST=3,
   BRE_AUTH_SCOPE_DEMO_BASKET_SESSION=4,
   BRE_AUTH_SCOPE_LIVE_DISABLED=5
  };

inline string ExecutionAuthorizationScopeLabel(const ENUM_BRE_EXECUTION_AUTHORIZATION_SCOPE scope)
  {
   switch(scope)
     {
      case BRE_AUTH_SCOPE_DRY_RUN_ONLY: return "DRY_RUN_ONLY";
      case BRE_AUTH_SCOPE_SIMULATED_ONLY: return "SIMULATED_ONLY";
      case BRE_AUTH_SCOPE_DEMO_SINGLE_REQUEST: return "DEMO_SINGLE_REQUEST";
      case BRE_AUTH_SCOPE_DEMO_BASKET_SESSION: return "DEMO_BASKET_SESSION";
      case BRE_AUTH_SCOPE_LIVE_DISABLED: return "LIVE_DISABLED";
      default: return "NONE";
     }
  }

#endif
