#ifndef BRE_DOMAIN_LIVE_SUBMISSION_SAFETY_REJECTION_REASON_MQH
#define BRE_DOMAIN_LIVE_SUBMISSION_SAFETY_REJECTION_REASON_MQH

enum ENUM_BRE_LIVE_SUBMISSION_SAFETY_REJECTION_REASON
  {
   BRE_LIVE_SAFETY_NONE=0,
   BRE_LIVE_SAFETY_LIVE_DISABLED=1,
   BRE_LIVE_SAFETY_GLOBAL_KILL_SWITCH=2,
   BRE_LIVE_SAFETY_BASKET_KILL_SWITCH=3,
   BRE_LIVE_SAFETY_DEMO_EXECUTION_DISABLED=4,
   BRE_LIVE_SAFETY_MANUAL_AUTH_REQUIRED=5,
   BRE_LIVE_SAFETY_TOKEN_MISSING=6,
   BRE_LIVE_SAFETY_TOKEN_INVALID=7,
   BRE_LIVE_SAFETY_TOKEN_EXPIRED=8,
   BRE_LIVE_SAFETY_TOKEN_CONSUMED=9,
   BRE_LIVE_SAFETY_TOKEN_BINDING_MISMATCH=10,
   BRE_LIVE_SAFETY_SESSION_CAP_EXCEEDED=11,
   BRE_LIVE_SAFETY_ACCOUNT_NOT_DEMO=12,
   BRE_LIVE_SAFETY_ACCOUNT_UNKNOWN=13,
   BRE_LIVE_SAFETY_ACCOUNT_TRADE_DISABLED=14,
   BRE_LIVE_SAFETY_TERMINAL_ALGO_DISABLED=15,
   BRE_LIVE_SAFETY_CHART_EA_TRADE_DISABLED=16,
   BRE_LIVE_SAFETY_BASKET_NOT_ACTIVE=17,
   BRE_LIVE_SAFETY_BASKET_LOCKED=18,
   BRE_LIVE_SAFETY_PROFILE_HASH_MISMATCH=19,
   BRE_LIVE_SAFETY_BASKET_VERSION_MISMATCH=20,
   BRE_LIVE_SAFETY_NOT_QUEUED_PREPARED=21,
   BRE_LIVE_SAFETY_ENVELOPE_EXPIRED=22,
   BRE_LIVE_SAFETY_STALE_QUOTE=23,
   BRE_LIVE_SAFETY_WIDE_SPREAD=24,
   BRE_LIVE_SAFETY_MARKET_UNAVAILABLE=25,
   BRE_LIVE_SAFETY_SYMBOL_CONSTRAINTS=26,
   BRE_LIVE_SAFETY_VOLUME_INVALID=27,
   BRE_LIVE_SAFETY_STOP_FREEZE_INVALID=28,
   BRE_LIVE_SAFETY_CONFLICTING_PENDING=29,
   BRE_LIVE_SAFETY_BASKET_RECONCILING_BLOCK=30,
   BRE_LIVE_SAFETY_DAILY_LOSS_GATE=31,
   BRE_LIVE_SAFETY_MAX_CONCURRENT_GATE=32,
   BRE_LIVE_SAFETY_EXECUTION_MODE_INVALID=33,
   BRE_LIVE_SAFETY_REQUEST_NOT_FOUND=34,
   BRE_LIVE_SAFETY_INTENT_NOT_ALLOWED=35,
   BRE_LIVE_SAFETY_VOLUME_EXCEEDS_DEMO_MAX=36,
   BRE_LIVE_SAFETY_TRIGGER_TOKEN_MISSING=37,
   BRE_LIVE_SAFETY_TRIGGER_TOKEN_CONSUMED=38,
   BRE_LIVE_SAFETY_SYMBOL_SESSION_LOCKED=39,
   BRE_LIVE_SAFETY_NOT_AUTHORIZED_FOR_SUBMISSION=40,
   BRE_LIVE_SAFETY_SUBMISSION_SESSION_CAP=41
  };

inline string LiveSubmissionSafetyRejectionReasonLabel(const ENUM_BRE_LIVE_SUBMISSION_SAFETY_REJECTION_REASON reason)
  {
   switch(reason)
     {
      case BRE_LIVE_SAFETY_LIVE_DISABLED: return "LIVE_DISABLED";
      case BRE_LIVE_SAFETY_GLOBAL_KILL_SWITCH: return "GLOBAL_KILL_SWITCH";
      case BRE_LIVE_SAFETY_BASKET_KILL_SWITCH: return "BASKET_KILL_SWITCH";
      case BRE_LIVE_SAFETY_DEMO_EXECUTION_DISABLED: return "DEMO_EXECUTION_DISABLED";
      case BRE_LIVE_SAFETY_MANUAL_AUTH_REQUIRED: return "MANUAL_AUTH_REQUIRED";
      case BRE_LIVE_SAFETY_TOKEN_MISSING: return "TOKEN_MISSING";
      case BRE_LIVE_SAFETY_TOKEN_INVALID: return "TOKEN_INVALID";
      case BRE_LIVE_SAFETY_TOKEN_EXPIRED: return "TOKEN_EXPIRED";
      case BRE_LIVE_SAFETY_TOKEN_CONSUMED: return "TOKEN_CONSUMED";
      case BRE_LIVE_SAFETY_TOKEN_BINDING_MISMATCH: return "TOKEN_BINDING_MISMATCH";
      case BRE_LIVE_SAFETY_SESSION_CAP_EXCEEDED: return "SESSION_CAP_EXCEEDED";
      case BRE_LIVE_SAFETY_ACCOUNT_NOT_DEMO: return "ACCOUNT_NOT_DEMO";
      case BRE_LIVE_SAFETY_ACCOUNT_UNKNOWN: return "ACCOUNT_UNKNOWN";
      case BRE_LIVE_SAFETY_ACCOUNT_TRADE_DISABLED: return "ACCOUNT_TRADE_DISABLED";
      case BRE_LIVE_SAFETY_TERMINAL_ALGO_DISABLED: return "TERMINAL_ALGO_DISABLED";
      case BRE_LIVE_SAFETY_CHART_EA_TRADE_DISABLED: return "CHART_EA_TRADE_DISABLED";
      case BRE_LIVE_SAFETY_BASKET_NOT_ACTIVE: return "BASKET_NOT_ACTIVE";
      case BRE_LIVE_SAFETY_BASKET_LOCKED: return "BASKET_LOCKED";
      case BRE_LIVE_SAFETY_PROFILE_HASH_MISMATCH: return "PROFILE_HASH_MISMATCH";
      case BRE_LIVE_SAFETY_BASKET_VERSION_MISMATCH: return "BASKET_VERSION_MISMATCH";
      case BRE_LIVE_SAFETY_NOT_QUEUED_PREPARED: return "NOT_QUEUED_PREPARED";
      case BRE_LIVE_SAFETY_ENVELOPE_EXPIRED: return "ENVELOPE_EXPIRED";
      case BRE_LIVE_SAFETY_STALE_QUOTE: return "STALE_QUOTE";
      case BRE_LIVE_SAFETY_WIDE_SPREAD: return "WIDE_SPREAD";
      case BRE_LIVE_SAFETY_MARKET_UNAVAILABLE: return "MARKET_UNAVAILABLE";
      case BRE_LIVE_SAFETY_SYMBOL_CONSTRAINTS: return "SYMBOL_CONSTRAINTS";
      case BRE_LIVE_SAFETY_VOLUME_INVALID: return "VOLUME_INVALID";
      case BRE_LIVE_SAFETY_STOP_FREEZE_INVALID: return "STOP_FREEZE_INVALID";
      case BRE_LIVE_SAFETY_CONFLICTING_PENDING: return "CONFLICTING_PENDING";
      case BRE_LIVE_SAFETY_BASKET_RECONCILING_BLOCK: return "BASKET_RECONCILING_BLOCK";
      case BRE_LIVE_SAFETY_DAILY_LOSS_GATE: return "DAILY_LOSS_GATE";
      case BRE_LIVE_SAFETY_MAX_CONCURRENT_GATE: return "MAX_CONCURRENT_GATE";
      case BRE_LIVE_SAFETY_EXECUTION_MODE_INVALID: return "EXECUTION_MODE_INVALID";
      case BRE_LIVE_SAFETY_REQUEST_NOT_FOUND: return "REQUEST_NOT_FOUND";
      case BRE_LIVE_SAFETY_INTENT_NOT_ALLOWED: return "INTENT_NOT_ALLOWED";
      case BRE_LIVE_SAFETY_VOLUME_EXCEEDS_DEMO_MAX: return "VOLUME_EXCEEDS_DEMO_MAX";
      case BRE_LIVE_SAFETY_TRIGGER_TOKEN_MISSING: return "TRIGGER_TOKEN_MISSING";
      case BRE_LIVE_SAFETY_TRIGGER_TOKEN_CONSUMED: return "TRIGGER_TOKEN_CONSUMED";
      case BRE_LIVE_SAFETY_SYMBOL_SESSION_LOCKED: return "SYMBOL_SESSION_LOCKED";
      case BRE_LIVE_SAFETY_NOT_AUTHORIZED_FOR_SUBMISSION: return "NOT_AUTHORIZED_FOR_SUBMISSION";
      case BRE_LIVE_SAFETY_SUBMISSION_SESSION_CAP: return "SUBMISSION_SESSION_CAP";
      default: return "NONE";
     }
  }

#endif
