#ifndef BRE_DOMAIN_PENDING_EXECUTION_CORRELATION_STATE_MQH
#define BRE_DOMAIN_PENDING_EXECUTION_CORRELATION_STATE_MQH

enum ENUM_BRE_PENDING_EXECUTION_CORRELATION_STATE
  {
   BRE_PENDING_CORRELATION_UNMATCHED=0,
   BRE_PENDING_CORRELATION_ORDER_ID=1,
   BRE_PENDING_CORRELATION_DEAL_ID=2,
   BRE_PENDING_CORRELATION_TICKET=3,
   BRE_PENDING_CORRELATION_MAGIC_COMMENT=4,
   BRE_PENDING_CORRELATION_FINGERPRINT=5,
   BRE_PENDING_CORRELATION_RECONCILING=6,
   BRE_PENDING_CORRELATION_RECONCILED=7
  };

inline string PendingExecutionCorrelationStateLabel(const ENUM_BRE_PENDING_EXECUTION_CORRELATION_STATE state)
  {
   switch(state)
     {
      case BRE_PENDING_CORRELATION_ORDER_ID: return "order_id";
      case BRE_PENDING_CORRELATION_DEAL_ID: return "deal_id";
      case BRE_PENDING_CORRELATION_TICKET: return "ticket";
      case BRE_PENDING_CORRELATION_MAGIC_COMMENT: return "magic_comment";
      case BRE_PENDING_CORRELATION_FINGERPRINT: return "fingerprint";
      case BRE_PENDING_CORRELATION_RECONCILING: return "reconciling";
      case BRE_PENDING_CORRELATION_RECONCILED: return "reconciled";
      default: return "unmatched";
     }
  }

#endif
