#ifndef BRE_DOMAIN_PREPARED_SUBMISSION_FAILURE_REASON_MQH
#define BRE_DOMAIN_PREPARED_SUBMISSION_FAILURE_REASON_MQH

enum ENUM_BRE_PREPARED_SUBMISSION_FAILURE_REASON
  {
   BRE_SUBMIT_FAIL_NONE=0,
   BRE_SUBMIT_FAIL_NOT_FOUND=1,
   BRE_SUBMIT_FAIL_NOT_QUEUED=2,
   BRE_SUBMIT_FAIL_NOT_PREPARED=3,
   BRE_SUBMIT_FAIL_ENVELOPE_EXPIRED=4,
   BRE_SUBMIT_FAIL_ENVELOPE_MISMATCH=5,
   BRE_SUBMIT_FAIL_ALREADY_SUBMITTED=6,
   BRE_SUBMIT_FAIL_BLOCKED_STATE=7,
   BRE_SUBMIT_FAIL_GATEWAY_REJECTED=8,
   BRE_SUBMIT_FAIL_GATEWAY_UNKNOWN=9,
   BRE_SUBMIT_FAIL_VALIDATION=10
  };

inline string PreparedSubmissionFailureReasonLabel(const ENUM_BRE_PREPARED_SUBMISSION_FAILURE_REASON reason)
  {
   switch(reason)
     {
      case BRE_SUBMIT_FAIL_NOT_FOUND: return "NOT_FOUND";
      case BRE_SUBMIT_FAIL_NOT_QUEUED: return "NOT_QUEUED";
      case BRE_SUBMIT_FAIL_NOT_PREPARED: return "NOT_PREPARED";
      case BRE_SUBMIT_FAIL_ENVELOPE_EXPIRED: return "ENVELOPE_EXPIRED";
      case BRE_SUBMIT_FAIL_ENVELOPE_MISMATCH: return "ENVELOPE_MISMATCH";
      case BRE_SUBMIT_FAIL_ALREADY_SUBMITTED: return "ALREADY_SUBMITTED";
      case BRE_SUBMIT_FAIL_BLOCKED_STATE: return "BLOCKED_STATE";
      case BRE_SUBMIT_FAIL_GATEWAY_REJECTED: return "GATEWAY_REJECTED";
      case BRE_SUBMIT_FAIL_GATEWAY_UNKNOWN: return "GATEWAY_UNKNOWN";
      case BRE_SUBMIT_FAIL_VALIDATION: return "VALIDATION";
      default: return "NONE";
     }
  }

#endif
