#ifndef BRE_DOMAIN_SIMULATED_BROKER_SUBMISSION_SCENARIO_MQH
#define BRE_DOMAIN_SIMULATED_BROKER_SUBMISSION_SCENARIO_MQH

enum ENUM_BRE_SIMULATED_BROKER_SUBMISSION_SCENARIO
  {
   BRE_SIM_SUBMIT_ACCEPT_ACK=0,
   BRE_SIM_SUBMIT_ACCEPT_FILL=1,
   BRE_SIM_SUBMIT_ACCEPT_PARTIAL_FILL_FILL=2,
   BRE_SIM_SUBMIT_ACCEPT_PARTIAL_FILL_REJECT=3,
   BRE_SIM_SUBMIT_REJECT_BEFORE_ACK=4,
   BRE_SIM_SUBMIT_ACCEPT_TIMEOUT=5,
   BRE_SIM_SUBMIT_ACCEPT_UNKNOWN=6,
   BRE_SIM_SUBMIT_DUPLICATE_ATTEMPT=7,
   BRE_SIM_SUBMIT_STALE_ENVELOPE=8,
   BRE_SIM_SUBMIT_EXPIRED_ENVELOPE=9
  };

inline string SimulatedBrokerSubmissionScenarioLabel(const ENUM_BRE_SIMULATED_BROKER_SUBMISSION_SCENARIO scenario)
  {
   switch(scenario)
     {
      case BRE_SIM_SUBMIT_ACCEPT_ACK: return "ACCEPT_ACK";
      case BRE_SIM_SUBMIT_ACCEPT_FILL: return "ACCEPT_FILL";
      case BRE_SIM_SUBMIT_ACCEPT_PARTIAL_FILL_FILL: return "ACCEPT_PARTIAL_FILL_FILL";
      case BRE_SIM_SUBMIT_ACCEPT_PARTIAL_FILL_REJECT: return "ACCEPT_PARTIAL_FILL_REJECT";
      case BRE_SIM_SUBMIT_REJECT_BEFORE_ACK: return "REJECT_BEFORE_ACK";
      case BRE_SIM_SUBMIT_ACCEPT_TIMEOUT: return "ACCEPT_TIMEOUT";
      case BRE_SIM_SUBMIT_ACCEPT_UNKNOWN: return "ACCEPT_UNKNOWN";
      case BRE_SIM_SUBMIT_DUPLICATE_ATTEMPT: return "DUPLICATE_ATTEMPT";
      case BRE_SIM_SUBMIT_STALE_ENVELOPE: return "STALE_ENVELOPE";
      case BRE_SIM_SUBMIT_EXPIRED_ENVELOPE: return "EXPIRED_ENVELOPE";
      default: return "NONE";
     }
  }

#endif
